server:
  port: 9090
eureka:
  client:
    service-url:
      defalutzone: http://localhost:8761/eureka/
spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-security?useUnicode=true&characterEncoding=utf-8&characterSetResult=utf-8&useSSL=false
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
feign:
  hystryix:
    enabled: true
